language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
env:
  - TEST_RANDOM_BUCKET=true
repo_token: 9WQMbVv4TBn4rST2F6mlSRENwiawzETQa
after_script: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
